name: Release

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Install cargo-wix
      run: cargo install cargo-wix

    - name: Download and Install WiX Toolset
      run: |
        wget https://github.com/wixtoolset/wix3/releases/download/v3.14.0.4916/wix311.zip
        unzip wix311.zip -d wix
        sudo mv wix /usr/local/wix
        sudo ln -s /usr/local/wix/bin/* /usr/local/bin

    - name: Run cargo wix
      run: cargo wix

    - name: Find MSI File
      id: find_msi
      run: |
        MSI_FILE=$(ls target/wix/*.msi | head -n 1)
        echo "MSI_FILE=$MSI_FILE" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload MSI to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.MSI_FILE }}
        asset_name: winch-<VERSION>-x86_64.msi
        asset_content_type: application/octet-stream
